-- AlterEnum
ALTER TYPE "LegalDocumentType" ADD VALUE IF NOT EXISTS 'PERSONERIA';
ALTER TYPE "LegalDocumentType" ADD VALUE IF NOT EXISTS 'PERMISO';
ALTER TYPE "LegalDocumentType" ADD VALUE IF NOT EXISTS 'FRECUENCIA';
