-- Completa requisito esperado y observaciones según M-SIG-01 (v. cambios 1),
-- INTE ISO 9001:2015 / INTE ISO 18788:2018 y documentos APPROVED en biblioteca.
-- Textos propios del SIG Alfa (paráfrasis de cumplimiento), no copia literal de la norma.

UPDATE "sig_requirements" AS r
SET
  "description" = v.descripcion,
  "observations" = v.observaciones,
  "isApplicable" = v.aplicable,
  "lastReviewedAt" = NOW()
FROM (
  VALUES
  ('ISO_9001','4', true,
   'Determinar y revisar el contexto, las partes interesadas, el alcance y los procesos del SGC de seguridad física y electrónica.',
   'Cumplimiento integrado en M-SIG-01 §4. Evidencia en biblioteca: F-SIG-01 (contexto), F-SIG-02 (partes interesadas), M-SIG-01 (alcance). Falta en biblioteca el mapa D-SIG-01 y la cadena D-SIG-02 citados por el manual. Revisión anual del contexto.'),
  ('ISO_18788','4', true,
   'Determinar el contexto de las operaciones de seguridad privada, incluida la cadena de suministro, subcontratistas y criterios de riesgo.',
   'M-SIG-01 §4.1.4–4.1.5: cadena de suministro (D-SIG-02, no está en biblioteca) y criterios de riesgo en P-SIG-03 (sí, aprobado). Contexto interno/externo en F-SIG-01 (aprobado). Revisar anualmente.'),
  ('ISO_9001','4.1', true,
   'Identificar cuestiones internas y externas que afectan la capacidad de lograr los resultados del servicio de seguridad y revisarlas de forma periódica.',
   'M-SIG-01: se documenta en F-SIG-01 (aprobado en biblioteca) y se revisa al menos una vez al año. Mantener el análisis vigente y llevarlo a la revisión por la dirección.'),
  ('ISO_18788','4.1', true,
   'Comprender el contexto interno y externo de las operaciones de seguridad, el mapeo de la cadena de suministro/subcontratistas y los criterios para valorar riesgos.',
   'F-SIG-01 cubre contexto interno/externo (aprobado). D-SIG-02 Cadena de suministros está citado en el manual y no aparece en la biblioteca: cargarlo o justificar. Criterios de riesgo: P-SIG-03 (aprobado).'),
  ('ISO_9001','4.2', true,
   'Determinar las partes interesadas pertinentes al SGC y sus requisitos, y darles seguimiento.',
   'M-SIG-01 §4.2: F-SIG-02 Matriz de partes interesadas (aprobado). Seguimiento anual. Verificar que clientes, colaboradores, Ministerio de Seguridad, comunidades y proveedores críticos estén actualizados.'),
  ('ISO_18788','4.2', true,
   'Determinar partes interesadas de las operaciones de seguridad (clientes, autoridades, personal, comunidades, subcontratistas) y sus requisitos, incluidos derechos humanos y legales.',
   'Misma matriz F-SIG-02 (aprobada). Complementar con F-LE-16 requisitos legales (aprobado) y M-RH-03 Manual de derechos humanos (aprobado). Revisión anual.'),
  ('ISO_9001','4.3', true,
   'Definir y mantener el alcance del SGC: prestación de seguridad física y electrónica en territorio nacional, con exclusiones justificadas.',
   'Alcance en M-SIG-01 (aprobado): Dirección General y Operaciones, más apoyo Comercial, Finanzas, Proveeduría, Transportes, RR.HH., Legal y Calidad. Exclusiones 9001: 8.3 diseño y desarrollo, y 7.1.5.2 trazabilidad de mediciones. Publicar el alcance y mantenerlo en la copia controlada.'),
  ('ISO_18788','4.3', true,
   'Definir el alcance de las operaciones de seguridad privada y las exclusiones justificadas de la norma 18788.',
   'M-SIG-01 excluye de 18788: 7.1.2.4 externalización/subcontratación, 8.4 aprehensión y revisión, y 8.5.2 operaciones de detención. El alcance declarado es seguridad física y electrónica en Costa Rica. Conservar la justificación en el manual.'),
  ('ISO_9001','4.4', true,
   'Establecer, implementar, mantener y mejorar el SGC y sus procesos, con secuencia, criterios, recursos, riesgos y evaluación.',
   'M-SIG-01 §4.4 remite a D-SIG-01 Mapa de procesos (no está en biblioteca), F-SIG-03 riesgos (aprobado), P-CORP-02, P-SIG-05 y P-SIG-04 (aprobados). Cargar el mapa de procesos o el equivalente vigente.'),
  ('ISO_18788','4.4', true,
   'Establecer el sistema de gestión de operaciones de seguridad, sus procesos e interacciones, y mejorarlo de forma continua.',
   'Procesos operativos citados: P-OP-01, P-OP-02, P-OP-04, P-OP-05 y P-OP-07 (todos aprobados). Falta D-SIG-01 en biblioteca. Riesgos en P-SIG-03 y F-SIG-03 (aprobados).'),
  ('ISO_9001','5', true,
   'La alta dirección demuestra liderazgo y compromiso con el SGC, la política, los roles y el enfoque al cliente.',
   'M-SIG-01 §5. Evidencias en biblioteca: PO-SIG-02 Declaración de conformidad, M-RH-01 puestos. No está PO-SIG-01 Política integrada citada por el manual: ubicarla o emitirla con F-SIG-15.'),
  ('ISO_18788','5', true,
   'La alta dirección lidera las operaciones de seguridad, la política integrada, la declaración de conformidad y la rendición de cuentas.',
   'PO-SIG-02 Declaración de conformidad está aprobada. Política integrada PO-SIG-01 no está en biblioteca. Roles en M-RH-01 (aprobado).'),
  ('ISO_9001','5.1', true,
   'Rendir cuentas del SGC, integrar los requisitos en el negocio, promover el enfoque a procesos y al cliente, y apoyar a los responsables.',
   'M-SIG-01 §5.1: enfoque al cliente vía medición de satisfacción (P-SGC-06 no está en biblioteca) y quejas P-SAC-01 (aprobado). Riesgos que afectan al cliente: F-SIG-03 (aprobado). Declaración: PO-SIG-02 (aprobada).'),
  ('ISO_18788','5.1', true,
   'La alta dirección rinde cuentas de las operaciones de seguridad, de la conformidad con la norma y de los recursos para el sistema.',
   'Declaración de conformidad PO-SIG-02 (aprobada). Comprometer recursos y comunicar la política; la política integrada PO-SIG-01 sigue ausente en biblioteca.'),
  ('ISO_9001','5.2', true,
   'Establecer, implementar, mantener y comunicar una política de la calidad adecuada al propósito, con compromiso de cumplir requisitos y de mejorar.',
   'El manual cita PO-SIG-01 Política integrada y su comunicación. En biblioteca no está ese código; sí están PO-SIG-02 (conformidad), PO-SIG-03 (denuncia) y PO-RH-03 (ética). Cargar o codificar la política integrada y evidenciar su difusión.'),
  ('ISO_18788','5.2', true,
   'Mantener una política de operaciones de seguridad alineada a requisitos legales, derechos humanos y mejora, y comunicarla.',
   'Misma brecha: PO-SIG-01 no está en biblioteca. Apoyos existentes: PO-SIG-03 Política de denuncia, PO-RH-03 Código de ética, M-RH-03 Derechos humanos (aprobados).'),
  ('ISO_9001','5.3', true,
   'Asignar y comunicar responsabilidades y autoridades del SGC (conformidad, procesos, informe a la dirección, enfoque al cliente).',
   'M-SIG-01 §5.3: M-RH-01 Manual de puestos (aprobado). El registro R-CORP-01 Matriz de responsabilidades citado no está en biblioteca: confirmar si vive dentro de M-RH-01.'),
  ('ISO_18788','5.3', true,
   'Definir responsabilidades y autoridades de las operaciones de seguridad, incluida la rendición de cuentas ante la alta dirección.',
   'M-RH-01 (aprobado) describe competencias y responsabilidades. Verificar que el responsable del SIG y los dueños de proceso estén nombrados y comunicados.'),
  ('ISO_9001','6', true,
   'Planificar riesgos y oportunidades, objetivos de la calidad y los cambios del SGC.',
   'M-SIG-01 §6. En biblioteca: P-SIG-03, F-SIG-03, F-LE-16, O-SIG-01. Faltan F-SIG-13 (indicadores), F-SIG-30 (plan de objetivos) y F-SIG-17 (cambios).'),
  ('ISO_18788','6', true,
   'Planificar el tratamiento del riesgo de las operaciones de seguridad, los requisitos legales y los objetivos de seguridad.',
   'P-SIG-03 y F-SIG-03 (aprobados). Legales: F-LE-16 (aprobado). Objetivos: O-SIG-01 (aprobado). Operación: P-OP-01, P-OP-02, P-OP-04, P-OP-05, P-OP-07 (aprobados).'),
  ('ISO_9001','6.1', true,
   'Determinar riesgos y oportunidades del SGC, planificar acciones, integrarlas a los procesos y evaluar su eficacia.',
   'F-SIG-03 y P-SIG-03 (aprobados). F-SIG-34 en biblioteca es «Control de matriz de riesgo» / también el manual lo usa como reporte de servicio no conforme: aclarar el uso real del formato.'),
  ('ISO_18788','6.1', true,
   'Abordar riesgos de operaciones de seguridad, requisitos legales y la consulta/comunicación de riesgos internos y externos.',
   'P-SIG-03 y F-SIG-03 (aprobados). F-LE-16 legales (aprobado), revisión anual por Legal y dueños de proceso. Comunicación de riesgos: P-SIG-08 y F-SIG-31 (aprobados).'),
  ('ISO_18788','6.1.2', true,
   'Identificar, acceder y evaluar el cumplimiento de requisitos legales y otros requisitos aplicables a las operaciones de seguridad.',
   'M-SIG-01: F-LE-16 Matriz de requisitos legales (aprobado). Debe contener el requisito, descripción, evidencia y frecuencia de actualización. Evaluación anual con fecha de revisión en observaciones.'),
  ('ISO_9001','6.2', true,
   'Establecer objetivos de la calidad medibles, coherentes con la política, y planificar qué, recursos, responsable, plazo y evaluación.',
   'O-SIG-01 Objetivos integrados (aprobado). El manual también cita F-SIG-13 Cuadro de indicadores y F-SIG-30 Planificación de objetivos: ninguno está en biblioteca. I-SIG-06 Elaboración y medición del indicador sí está aprobado: usarlo como método y cargar el cuadro vigente.'),
  ('ISO_18788','6.2', true,
   'Establecer objetivos de las operaciones de seguridad y del tratamiento del riesgo, y planificar cómo lograrlos.',
   'O-SIG-01 (aprobado) y P-SIG-03 (aprobado). Despliegue operativo en P-OP-07, P-OP-01, P-OP-02, P-OP-04 y P-OP-05 (aprobados). Falta F-SIG-30 en biblioteca.'),
  ('ISO_9001','6.3', true,
   'Planificar los cambios del SGC (propósito, integridad, recursos, responsabilidades) antes de implementarlos.',
   'M-SIG-01 §6.3: F-SIG-17 Planificación de los cambios (no está en biblioteca) y P-CORP-02 Mejora continua (aprobado). Crear o cargar F-SIG-17 y usarlo en cambios de procesos, alcance o documentos.'),
  ('ISO_9001','7', true,
   'Proveer personas, infraestructura, ambiente, seguimiento y conocimiento necesarios para el SGC y el servicio.',
   'M-SIG-01 §7. Personas: M-RH-01. Infraestructura y flotilla: P-TR-01 (aprobado). Ambiente de trabajo y SSO: PO-SO-01 (aprobado). 7.1.5.2 queda excluido del alcance.'),
  ('ISO_18788','7', true,
   'Proveer la estructura, personas, seguros, recursos financieros y apoyo para operar el sistema de seguridad.',
   'M-RH-01 (aprobado). Finanzas: P-FI-01 y P-FI-02 (aprobados). Compras: P-PV-02 (aprobado). Externalización 7.1.2.4 está excluida en el alcance del manual.'),
  ('ISO_9001','7.1', true,
   'Determinar y proporcionar recursos (personas, infraestructura, ambiente, medición y conocimiento organizacional).',
   'Personas en M-RH-01. Mantenimiento de móviles en P-TR-01. Conocimiento: el manual cita F-RH-56 (no está con ese código en biblioteca). Exclusión documentada: 7.1.5.2 trazabilidad metrológica.'),
  ('ISO_18788','7.1', true,
   'Asegurar estructura organizacional, competencias, seguros y procedimientos financieros/administrativos de las operaciones de seguridad.',
   'Estructura y competencias: M-RH-01 (aprobado). Administración: P-FI-01, P-FI-02, P-PV-02 (aprobados). El apartado 7.1.2.4 de subcontratación está excluido; el control de proveedores externos de 9001 se cubre en 8.4.'),
  ('ISO_18788','7.1.2.4', false,
   'No aplica: el alcance del SIG (M-SIG-01) excluye la externalización y subcontratación de operaciones de seguridad de ISO 18788.',
   'Exclusión declarada en M-SIG-01 §4.3. Si en la práctica se subcontrata vigilancia o servicios críticos, reabrir el requisito y controlarlo (P-PV-01). Mientras no aplique, conservar la justificación en el manual.'),
  ('ISO_9001','7.1.5.2', false,
   'No aplica: el servicio de seguridad no requiere trazabilidad metrológica ni calibración de equipos de medición.',
   'Exclusión declarada en M-SIG-01 §4.3. El seguimiento del servicio se hace con indicadores, supervisión de puestos (P-OP-04) e informes (F-OP-32), no con equipos calibrados.'),
  ('ISO_9001','7.2', true,
   'Determinar la competencia necesaria, asegurar que las personas sean competentes, formar cuando haga falta y conservar evidencia.',
   'M-SIG-01 §7.2: perfiles en M-RH-01. Procedimientos P-RH-07 y P-RH-08 (aprobados). Asistencia: F-RH-07 (aprobado). El manual cita F-RH-41 evaluación de eficacia y F-RH-56/57 planes: no están con esos códigos; localizar el registro vigente de eficacia de la capacitación.'),
  ('ISO_18788','7.2', true,
   'Asegurar competencia del personal de seguridad (selección, inducción, entrenamiento y evaluación), incluida conciencia de derechos humanos y uso de la fuerza.',
   'P-RH-08 entrenamiento operativo (aprobado), M-RH-03 derechos humanos y M-OP-05 uso de la fuerza (aprobados). Conservar expedientes y F-RH-07. Verificar evaluación de eficacia de la formación.'),
  ('ISO_9001','7.3', true,
   'Asegurar que el personal conozca la política, los objetivos, su contribución al SIG y las consecuencias de no cumplir.',
   'M-SIG-01: se asegura con P-SIG-08 Comunicaciones (aprobado) y la inducción P-RH-07 (aprobado). Falta evidencia explícita de difusión de PO-SIG-01 porque esa política no está cargada.'),
  ('ISO_18788','7.3', true,
   'Asegurar conciencia del personal sobre derechos humanos, uso de la fuerza, denuncia y su papel en las operaciones de seguridad.',
   'Documentos aprobados: M-RH-03, M-OP-05, PO-SIG-03 Política de denuncia, PO-RH-03 Código de ética, P-SIG-08. Incluir estos temas en inducción (P-RH-07 / P-RH-08) y conservar asistencia.'),
  ('ISO_9001','7.4', true,
   'Determinar las comunicaciones internas y externas del SGC: qué, cuándo, a quién, cómo y quién comunica.',
   'P-SIG-08 y F-SIG-31 Matriz de comunicaciones (ambos aprobados). Mantener la matriz al día (clientes, autoridades, personal).'),
  ('ISO_18788','7.4', true,
   'Gestionar comunicaciones operacionales, de riesgos, de quejas y de la política de denuncia.',
   'P-SIG-08 y F-SIG-31 (aprobados). Quejas: P-SAC-01 y PO-SAC-01 (aprobados). Denuncia: PO-SIG-03 (aprobada). Verificar que el canal anónimo esté comunicado al personal.'),
  ('ISO_9001','7.5', true,
   'Crear, actualizar y controlar la información documentada requerida por el SGC (identificación, formato, aprobación, distribución y retención).',
   'P-SIG-01 Control de información documentada (aprobado). Formatos F-SIG-07 a F-SIG-12, F-SIG-15 y F-SIG-20 (aprobados). La biblioteca de Alfa One es la copia controlada. El manual aún menciona una base «SFD»: alinear esa referencia con Alfa One.'),
  ('ISO_18788','7.5', true,
   'Controlar la información documentada de las operaciones de seguridad, incluidos registros de incidentes, fuerza, personal y quejas.',
   'Mismo P-SIG-01 (aprobado). Registros operativos y de derechos humanos deben conservarse según el procedimiento. Incidentes y uso de la fuerza: confirmar el registro vigente (el manual no nombra un único formato).'),
  ('ISO_9001','8', true,
   'Planificar y controlar la prestación del servicio de seguridad para cumplir los requisitos del cliente y los legales.',
   'Núcleo operativo en biblioteca: P-OP-07, P-OP-01, P-OP-05, P-OP-06, F-OP-01 y F-VT no siempre codificado. 8.3 diseño está excluido.'),
  ('ISO_18788','8', true,
   'Planificar y controlar las operaciones de seguridad respetando derechos humanos, uso de la fuerza y gestión de incidentes.',
   'P-OP-07 y supervisión P-OP-04 / P-OP-05 (aprobados). DD.HH.: M-RH-03. Fuerza: M-OP-05. Exclusiones de alcance: 8.4 aprehensión y 8.5.2 detención.'),
  ('ISO_9001','8.1', true,
   'Planificar y controlar la operación: requisitos del servicio, criterios, recursos, control de cambios y salidas no conformes.',
   'P-OP-07 Planificación y realización del servicio y O-SIG-01 (aprobados). Ficha del puesto: F-OP-01 (aprobado). Cambios de servicio: P-OP-06 y P-VT-05 (P-VT-05 no apareció en biblioteca: confirmar código).'),
  ('ISO_18788','8.1', true,
   'Planificar las funciones de seguridad y prevenir acontecimientos indeseables, con criterios de desempeño.',
   'P-OP-07, P-OP-01, P-OP-02, P-OP-04 y P-OP-05 (aprobados). Anomalías: F-OP-32 (aprobado). Derechos humanos en 8.1.3.'),
  ('ISO_18788','8.1.3', true,
   'Respetar los derechos humanos en las operaciones de seguridad y formar al personal en esa obligación.',
   'M-RH-03 Manual de derechos humanos (aprobado) y PO-RH-03 ética (aprobado). Incluir el tema en entrenamiento P-RH-08. Conservar evidencia de capacitación y de tratamiento de quejas (P-SAC-01).'),
  ('ISO_9001','8.2', true,
   'Comunicarse con el cliente, determinar y revisar los requisitos del servicio antes de comprometerse, y controlar los cambios.',
   'M-SIG-01: P-OP-07, F-OP-01 Ficha de generalidades, F-OP-04 seguimiento de apertura, F-VT-03 revisión de ofertas (F-VT-03 no está en biblioteca). Quejas: P-SAC-01 (aprobado). Satisfacción P-SGC-06 no está cargada. Adendas: confirmar P-VT-05.'),
  ('ISO_18788','8.3', true,
   'Controlar el uso de la fuerza: autorización, gradualidad, fuerza menos letal y letal, apoyo a la ley y formación.',
   'M-OP-05 Manual de uso de la fuerza (aprobado). No confundir con el 8.3 de ISO 9001 (diseño), que está excluido. Verificar que la formación en uso de la fuerza quede en el plan P-RH-08 y que los incidentes con armas se investiguen (8.8).'),
  ('ISO_9001','8.3', false,
   'No aplica: Alfa presta servicios y no diseña ni desarrolla productos. Exclusión del alcance del SGC.',
   'Exclusión explícita en M-SIG-01 §4.3 y §8.3. El código 8.3 de ISO 18788 (uso de la fuerza) sí aplica y se gestiona con M-OP-05.'),
  ('ISO_9001','8.4', true,
   'Controlar procesos, productos y servicios de proveedores externos: selección, tipo de control e información que se les entrega.',
   'P-PV-01 Selección y evaluación de proveedores, P-PV-02 y P-PV-03 (aprobados). Conservar evaluaciones. No aplica la aprehensión de 18788 (otro 8.4).'),
  ('ISO_18788','8.4', false,
   'No aplica: el alcance del SIG excluye aprehensión y revisión (8.4 / 8.4.1 / 8.4.2 de ISO 18788).',
   'Exclusión en M-SIG-01 §4.3. El control de proveedores externos se cubre por ISO 9001 8.4 (P-PV-01/02/03), no por este apartado.'),
  ('ISO_9001','8.5', true,
   'Prestar el servicio en condiciones controladas: información, competencia, seguimiento, identificación, propiedad del cliente y control de cambios.',
   'P-OP-01, P-OP-04, P-OP-05 y P-OP-06 (aprobados). Anomalías: F-OP-32. Capacitación: F-RH-07. Actividades posteriores a la entrega: P-OP-06 Atención al cliente.'),
  ('ISO_18788','8.5', true,
   'Controlar la prestación de las operaciones de seguridad. Las operaciones de detención están fuera del alcance.',
   'Prestación cubierta por P-OP-01/04/05 (aprobados). 8.5.2 detención está excluido. Identificación de personal y uniformes registrados ante la Dirección de Servicios de Seguridad Privada (M-SIG-01 §8.6.a.4).'),
  ('ISO_18788','8.5.2', false,
   'No aplica: el alcance del SIG excluye operaciones de detención.',
   'Exclusión declarada en M-SIG-01 §4.3. Si un contrato exigiera detención, habría que reabrir el requisito y documentar el procedimiento antes de operar.'),
  ('ISO_9001','8.6', true,
   'Liberar el servicio solo cuando se hayan cumplido las verificaciones planificadas y conservar evidencia de la conformidad y de quién autoriza.',
   'M-SIG-01: disposiciones del cliente en la revisión de ofertas y ejecución con P-OP-05 (aprobado). F-VT-03 no está en biblioteca: usar F-OP-04 y la ficha F-OP-01 como evidencia de liberación/apertura, o cargar F-VT-03.'),
  ('ISO_9001','8.7', true,
   'Identificar y controlar salidas no conformes del servicio, corregir, autorizar liberación cuando proceda y conservar el registro.',
   'P-SIG-10 Control de servicios no conformes (aprobado). El manual pide F-SIG-34 como reporte de no conformes; en biblioteca F-SIG-34 está titulado como control de matriz de riesgo: unificar el formato o el título para no mezclar riesgo y servicio no conforme.'),
  ('ISO_18788','8.7', true,
   'Controlar el servicio de seguridad no conforme y prevenir su entrega o continuación no intencionada.',
   'Mismo P-SIG-10 (aprobado) y supervisión P-OP-04 con F-OP-32 (aprobado). Aclarar el registro F-SIG-34.'),
  ('ISO_18788','8.8', true,
   'Identificar, reportar e investigar incidentes (incluida fuerza, armas, lesiones, abusos y quejas) y mantener una política de denuncia.',
   'PO-SIG-03 Política de denuncia y P-SAC-01 quejas (aprobados). El manual describe el deber de investigar incidentes graves pero no cita un procedimiento único en biblioteca: definir y cargar el procedimiento de gestión de incidentes (módulo Incidentes del SIG) y ligar evidencias.'),
  ('ISO_9001','9', true,
   'Hacer seguimiento, medir, analizar y evaluar el desempeño; auditar internamente y revisar el SGC por la dirección.',
   'M-SIG-01 §9. Auditoría: P-SIG-05, F-SIG-21 a F-SIG-24 (aprobados). Revisión: P-SIG-04 y F-SIG-18 (aprobados). F-SIG-19 seguimiento de pendientes no está en biblioteca.'),
  ('ISO_18788','9', true,
   'Evaluar el desempeño de las operaciones de seguridad, el cumplimiento legal, los ejercicios/pruebas, la auditoría interna y la revisión por la dirección.',
   'Legales: evaluación anual en F-LE-16. Auditoría y revisión: mismos P-SIG-05 y P-SIG-04. Ejercicios y pruebas (9.1.3): el manual los exige y no hay procedimiento nombrado en biblioteca.'),
  ('ISO_9001','9.1', true,
   'Definir qué se sigue y mide, métodos, cuándo y quién analiza; evaluar satisfacción del cliente y usar los resultados para mejorar.',
   'Indicadores según I-SIG-06 (aprobado) y fichas de proceso. Si no se cumple lo planificado: P-SIG-02 (aprobado). Satisfacción: P-SGC-06 no está en biblioteca; quejas sí (P-SAC-01). Resultados a revisión por la dirección (F-SIG-18).'),
  ('ISO_18788','9.1', true,
   'Medir el desempeño de las operaciones de seguridad y evaluar el cumplimiento de requisitos legales y otros requisitos.',
   'F-LE-16 con fecha de última revisión (aprobado). Supervisión de puestos P-OP-04 y F-OP-32. Llevar resultados a F-SIG-18.'),
  ('ISO_18788','9.1.3', true,
   'Realizar ejercicios y pruebas basados en el riesgo para comprobar que los planes y procedimientos de seguridad funcionan.',
   'M-SIG-01 §9.1.3.a lo exige y no hay procedimiento ni registro aprobado en biblioteca con ese fin. Definir frecuencia, escenarios (intrusión, fuerza, emergencia) y conservar acta. Relacionar con M-SO-01 Manual de emergencias (aprobado).'),
  ('ISO_9001','9.2', true,
   'Auditar el SGC a intervalos planificados, con programa, auditores competentes, informe y tratamiento de no conformidades.',
   'P-SIG-05, F-SIG-21 Programa, F-SIG-22 Plan, F-SIG-23 Informe, F-SIG-24 Lista de verificación y F-SIG-33 Evaluación de auditores (aprobados). Criterio: ISO 9001, ISO 18788 (INTE/ISO 19011 como guía de auditoría, PDF en cargas) y el propio SIG. NC según P-SIG-02.'),
  ('ISO_18788','9.2', true,
   'Auditar las operaciones de seguridad frente a ISO 18788 y a los controles del SIG, incluyendo derechos humanos y uso de la fuerza cuando aplique.',
   'Mismo programa F-SIG-21 y procedimiento P-SIG-05. La lista F-SIG-24 debe cubrir cláusulas 18788 aplicables (no las excluidas). Acciones: P-SIG-02.'),
  ('ISO_9001','9.3', true,
   'La alta dirección revisa el SGC de forma planificada (entradas de desempeño, auditorías, clientes, riesgos, oportunidades) y conserva decisiones y acciones.',
   'P-SIG-04 y F-SIG-18 Minuta de revisión por la dirección (aprobados). F-SIG-19 seguimiento de pendientes no está en biblioteca: dar seguimiento con acciones en P-SIG-02 o cargar el formato.'),
  ('ISO_18788','9.3', true,
   'La alta dirección revisa la idoneidad de las operaciones de seguridad, el cumplimiento legal, incidentes y resultados de auditoría.',
   'Misma revisión P-SIG-04 / F-SIG-18. Incluir en la agenda: F-LE-16, incidentes, quejas (P-SAC-01), uso de la fuerza y objetivos O-SIG-01.'),
  ('ISO_9001','10', true,
   'Mejorar el SGC: reaccionar ante no conformidades, eliminar causas y mejorar de forma continua la idoneidad del sistema.',
   'P-SIG-02 Acciones correctivas (aprobado) y P-CORP-02 Mejora continua (aprobado). Entradas: auditorías, quejas, servicios no conformes (P-SIG-10) y revisión por la dirección.'),
  ('ISO_18788','10', true,
   'Mejorar las operaciones de seguridad a partir de incidentes, quejas, auditorías y revisión por la dirección.',
   'P-SIG-02 y P-CORP-02 (aprobados). Cerrar el ciclo de incidentes (8.8) con acción correctiva cuando haya causa sistémica.'),
  ('ISO_9001','10.1', true,
   'Determinar oportunidades de mejora del servicio y del SGC y actuar para cumplir requisitos y aumentar la satisfacción.',
   'P-CORP-02 y resultados de P-SAC-01 / indicadores. Llevar oportunidades a la revisión por la dirección.'),
  ('ISO_9001','10.2', true,
   'Ante una no conformidad: corregir, analizar causa, implementar acción, revisar eficacia y actualizar riesgos y documentos si hace falta.',
   'P-SIG-02 (aprobado). Orígenes: auditoría (F-SIG-23), servicio no conforme (P-SIG-10), quejas (P-SAC-01). Verificar eficacia y conservar el registro. Si el riesgo cambia, actualizar F-SIG-03.'),
  ('ISO_18788','10.2', true,
   'Tratar no conformidades de operaciones de seguridad (incluidas las de derechos humanos, fuerza o legales) con acción correctiva y verificación de eficacia.',
   'P-SIG-02 (aprobado). Incidentes graves del §8.8 deben terminar en investigación y, si aplica, en acción correctiva. Política de denuncia PO-SIG-03 ya está aprobada.'),
  ('ISO_9001','10.3', true,
   'Mejorar continuamente la idoneidad, adecuación y eficacia del SGC usando análisis, auditorías y la revisión por la dirección.',
   'Ciclo: indicadores (I-SIG-06), auditoría (P-SIG-05), revisión (P-SIG-04) y mejora (P-CORP-02 / P-SIG-02), todos aprobados salvo el cuadro F-SIG-13.')
) AS v(norma, codigo, aplicable, descripcion, observaciones)
JOIN "sig_standards" s ON s.code = v.norma
WHERE r."standardId" = s.id
  AND r.code = v.codigo;
