import type { NotificationPriority } from "@prisma/client";

/** Catálogo estático de tipos de evento (semilla + referencia). */
export type NotificationEventDef = {
  code: string;
  moduleKey: string;
  label: string;
  description: string;
  priority: NotificationPriority;
  icon: string;
  permissionKey?: string;
  hrefTemplate?: string;
  /** Roles que pueden recibir este tipo (códigos Role.code). */
  roleCodes: string[];
};

export const NOTIFICATION_EVENT_CATALOG: NotificationEventDef[] = [
  // Tickets TI
  {
    code: "tickets.created",
    moduleKey: "ticketsTi",
    label: "Ticket creado",
    description: "Nuevo ticket registrado en el sistema",
    priority: "INFO",
    icon: "ticket-plus",
    permissionKey: "ticketsTi.centro",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.assigned",
    moduleKey: "ticketsTi",
    label: "Ticket asignado",
    description: "Un ticket fue asignado a un técnico",
    priority: "INFO",
    icon: "user-check",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.updated",
    moduleKey: "ticketsTi",
    label: "Ticket actualizado",
    description: "Cambios en un ticket",
    priority: "INFO",
    icon: "ticket",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.priority_changed",
    moduleKey: "ticketsTi",
    label: "Prioridad cambiada",
    description: "Cambio de prioridad en ticket",
    priority: "WARNING",
    icon: "alert-triangle",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
  {
    code: "tickets.status_changed",
    moduleKey: "ticketsTi",
    label: "Estado cambiado",
    description: "Cambio de estado en ticket",
    priority: "INFO",
    icon: "refresh-cw",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.comment",
    moduleKey: "ticketsTi",
    label: "Comentario en ticket",
    description: "Nuevo comentario en un ticket",
    priority: "INFO",
    icon: "message-square",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.attachment",
    moduleKey: "ticketsTi",
    label: "Adjunto en ticket",
    description: "Nuevo archivo adjunto",
    priority: "INFO",
    icon: "paperclip",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.reopened",
    moduleKey: "ticketsTi",
    label: "Ticket reabierto",
    description: "Un ticket cerrado fue reabierto",
    priority: "WARNING",
    icon: "rotate-ccw",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.closed",
    moduleKey: "ticketsTi",
    label: "Ticket cerrado",
    description: "Ticket resuelto o cerrado",
    priority: "SUCCESS",
    icon: "check-circle",
    permissionKey: "ticketsTi.tickets",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR", "CONSULTA"],
  },
  {
    code: "tickets.sla_warning",
    moduleKey: "ticketsTi",
    label: "Alerta SLA",
    description: "Ticket próximo a vencer SLA",
    priority: "URGENT",
    icon: "clock",
    permissionKey: "ticketsTi.centro",
    hrefTemplate: "/tickets-ti/{entityId}",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
  // Plataforma / usuarios
  {
    code: "platform.user_created",
    moduleKey: "plataforma",
    label: "Nuevo usuario",
    description: "Se registró un nuevo usuario",
    priority: "INFO",
    icon: "user-plus",
    permissionKey: "plataforma.users",
    hrefTemplate: "/admin/users",
    roleCodes: ["ADMIN"],
  },
  {
    code: "platform.role_changed",
    moduleKey: "plataforma",
    label: "Cambio de rol",
    description: "Rol de usuario modificado",
    priority: "WARNING",
    icon: "shield",
    permissionKey: "plataforma.users",
    hrefTemplate: "/admin/users",
    roleCodes: ["ADMIN"],
  },
  {
    code: "platform.critical_config",
    moduleKey: "plataforma",
    label: "Configuración crítica",
    description: "Cambio en configuración sensible",
    priority: "ERROR",
    icon: "settings",
    permissionKey: "plataforma.catalogs",
    hrefTemplate: "/admin/catalogs",
    roleCodes: ["ADMIN"],
  },
  // Inventario
  {
    code: "inventory.asset_created",
    moduleKey: "inventario",
    label: "Nuevo activo",
    description: "Activo registrado en inventario",
    priority: "INFO",
    icon: "package",
    permissionKey: "inventario.assets",
    hrefTemplate: "/inventory",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
  {
    code: "inventory.asset_assigned",
    moduleKey: "inventario",
    label: "Activo asignado",
    description: "Activo asignado a contrato o ubicación",
    priority: "INFO",
    icon: "link",
    permissionKey: "inventario.assets",
    hrefTemplate: "/inventory",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
  {
    code: "inventory.warranty_expiring",
    moduleKey: "inventario",
    label: "Garantía por vencer",
    description: "Garantía de activo próxima a expirar",
    priority: "WARNING",
    icon: "calendar-clock",
    permissionKey: "inventario.assets",
    hrefTemplate: "/inventory",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
  // Reportes
  {
    code: "reports.generated",
    moduleKey: "core",
    label: "Reporte generado",
    description: "Reporte listo para consulta",
    priority: "SUCCESS",
    icon: "file-bar-chart",
    permissionKey: "core.dashboard_ejecutivo",
    hrefTemplate: "/dashboard",
    roleCodes: ["ADMIN", "SUPERVISOR"],
  },
];
