-- Corrección NAF: abono mensual mal cargado al período 2025.
-- Empleado 03-099396 (MORALES CARVAJAL MAGALY).
-- El devengo del 2026-06-03 debe abrir el período 2026 (junio post-aniversario 03-05).
--
-- Requiere: GRANT UPDATE ON NAF5.ARPLVAC TO <usuario>;
-- Ejecutar como dueño NAF5 o usuario con UPDATE.

SET DEFINE OFF;

SELECT ROWID, NO_CIA, NO_EMPLE,
       TO_CHAR(GESTION,'YYYY-MM-DD') GESTION,
       TO_CHAR(FECHA_MOV,'YYYY-MM-DD') FECHA_MOV,
       ORIGEN, TIPO_MOV, DIAS, PERIODO
  FROM NAF5.ARPLVAC
 WHERE NO_CIA = '03'
   AND NO_EMPLE = '099396'
   AND TIPO_MOV = '+'
   AND PERIODO = 2025
   AND ORIGEN = 'P'
   AND DIAS = 1
   AND TRUNC(GESTION) = DATE '2026-06-03';

UPDATE NAF5.ARPLVAC
   SET PERIODO = 2026
 WHERE NO_CIA = '03'
   AND NO_EMPLE = '099396'
   AND TIPO_MOV = '+'
   AND PERIODO = 2025
   AND ORIGEN = 'P'
   AND DIAS = 1
   AND TRUNC(GESTION) = DATE '2026-06-03';

-- Debe afectar exactamente 1 fila
SELECT PERIODO,
       SUM(CASE WHEN TIPO_MOV='+' THEN ABS(DIAS) ELSE 0 END) GANADOS,
       SUM(CASE WHEN TIPO_MOV='-' THEN ABS(DIAS) ELSE 0 END) DISFRUTADOS
  FROM NAF5.ARPLVAC
 WHERE NO_CIA = '03' AND NO_EMPLE = '099396' AND PERIODO IN (2025, 2026)
 GROUP BY PERIODO
 ORDER BY 1;

COMMIT;
